site_name: Teamstudio Adviser 6.7

nav:
  - 'index.md'
  - 'Installation':
    - 'installing.md'
    - 'importing.md'
  - 'Using Teamstudio Adviser':
    - 'overview.md'
    - 'catalog.md'
    - 'usage.md'
    - 'complexity.md'
    - 'guidance.md'
    - 'jobs.md'
    - 'filters.md'
    - 'tags.md'
    - 'exporting.md'
  - 'Settings':
    - 'settings_servers.md'
    - 'settings_filters.md'
    - 'settings_scans.md'
    - 'settings_complexity.md'
  - 'release.md'

theme:
  name: material

extra:
  alternate:
    - name: English
      link: ./
      lang: en
    - name: 日本語
      link: ./ja/
      lang: ja
      
markdown_extensions:
  - admonition
  - md_in_html
  - pymdownx.highlight
  - pymdownx.superfences
  
plugins:
  - search
  - i18n:
      default_language: en
      languages:
        ja: 日本語
      nav_translations:
        ja:
          Installation: Teamstudio Adviser のインストール
          Using Teamstudio Adviser: Teamstudio Adviser の使い方
          Settings: 設定